blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'blogweb_blog'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^detalle/(?P<slug>[\w-]+)/$', views.detail_entry, name='detail_entry'),
    url(r'^autor/(?P<username>[\w-]+)/$', views.list_author, name='list_author'),
    url(r'^etiqueta/(?P<slug>[\w-]+)/$', views.list_tag, name='list_tag'),
]

okeanos/urls.py
from django.contrib import admin
from django.views.generic import TemplateView
from django.views.i18n import JavaScriptCatalog

from settings import MEDIA_URL, MEDIA_ROOT
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from .views import home
from django.conf.urls import include, url

urlpatterns = i18n_patterns(
    url(r'^admin/', include(admin.site.urls), name='django-admin'),
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    url(r'^$', home, name='home'),
    url(r'^blog/', include('blog.urls', namespace='blog-app'), name='blog-index'),
    url(r'^enviado/$', TemplateView.as_view(template_name="web/enviado.html"), name='enviado'),
) + static(MEDIA_URL, document_root=MEDIA_ROOT)

blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import datetime
from os.path import basename

# Create your models here.
from django.db import models
from django.template.defaultfilters import truncatechars  # or truncatewords
from django.utils.translation import ugettext as _, ugettext_lazy
from django_hosts.resolvers import reverse
from ckeditor.fields import RichTextField
from easy_thumbnails.fields import ThumbnailerImageField
from django.core import urlresolvers
from django.contrib.contenttypes.models import ContentType

now = datetime.datetime.now()

CONTENT_CHOICES = [
    ('NU', _("Nuevo")),
    ('PR', _("Proyecto")),
    ('PO', _("Posteo")),
    ('OT', _("Otro")),
    ('EV', _("Evento")),
]


class Etiqueta(models.Model):
    titulo = models.CharField(_('titulo'), max_length=30)
    slug = models.SlugField(
        _('slug'), null=True, blank=True,
        help_text='Slug que genera la url de la etiqueta', )

    def __unicode__(self):
        return '%s' % self.titulo

    class Meta:
        ordering = ('titulo',)
        verbose_name = _('etiqueta')
        verbose_name_plural = _('etiquetas')


class EntradaQuerySet(models.QuerySet):
    def publicado(self):
        return self.activo().filter(fecha_publicacion__lte=datetime.datetime.now())

    def activo(self):
        return self.filter(visible=True)


class Entrada(models.Model):
    # metadata
    creacion = models.DateTimeField(_('creación'), null=True, auto_created=True, editable=False)
    modificacion = models.DateTimeField(_('modificación'), auto_now=True, editable=False)
    fecha_publicacion = models.DateTimeField(
        verbose_name=_("fecha de publicación"), default=datetime.datetime.now,
        help_text="Para que una publicación sea publicada, debe estar activa y su fecha de publicación debe estar en el pasado", )
    autor = models.ForeignKey(
        'auth.User',
        verbose_name=_('autor'), )
    slug = models.SlugField(
        _('slug'),
        unique_for_date='fecha_publicacion',
        help_text='Debe ser unica en el mes y sirve para generar la url asociada, se genera automaticamente', )
    # if redirect to other site
    url_externa = models.URLField(
        _("url externa"), null=True, blank=True,
        help_text="Si se deja vacío este campo, los links para ver más detalles redireccionarán dentro del sitio al detalle. "
                  "Al ingresar una URL en este campo se redireccionará a este cuando se pidan detalles ")
    # content in publication
    tipo_publicacion = models.CharField(
        _('tipo de publicación'), max_length=2, choices=CONTENT_CHOICES, default='PO',
        help_text='Puede ser cualquier cosa: Eventos, posteos, proyectos, etc..')
    titulo = models.CharField(_('titulo'), max_length=200, help_text='Titulo de la publicación', )
    subtitulo = models.CharField(_('subtitulo'), max_length=200, blank=True, null=True,
                                 help_text='Subtitulo de la publicación', )
    ubicacion = models.CharField(_('ubicación'), max_length=40, blank=True, null=True)
    resumen = models.CharField(_('resumen'), max_length=300, blank=True, null=True)
    contenido = RichTextField(_('contenido'), blank=True, null=True)

    objects = EntradaQuerySet.as_manager()

    visible = models.BooleanField(
        _('se encuentra visible'),
        help_text=
        "Marque para hacer esta entrada en vivo (ver también la fecha de publicación). "
        "Tenga en cuenta que los administradores (como usted) tienen permiso para previsualizar "
        "Entradas inactivas mientras que el público en general no",
        default=False,
    )

    # Options
    etiqueta = models.ManyToManyField(Etiqueta,
                                      verbose_name=_('etiqueta'),
                                      related_name='entry_tag',
                                      blank=True)
    slider = models.BooleanField(
        _('activo en el slider'), default=False,
        help_text=
        "Marque para que sea visible en el slider "
        "Se visualizará primero el inicial y luego los que sean visibles en slider "
        "Pueden marcar hasta 6 para ser visibles, es necesaria una imagen, de no ser subida una imágen no se mostrará ",
    )
    comentarios_facebook = models.BooleanField(
        _('comentarios de Facebook'),
        help_text=
        "Marque para que sea visible el plugin de facebook para realizar comentarios "
        "No se tendrá mayor control sobre los comentarios ",
        default=False,
    )

    def get_admin_url(self):
        content_type = ContentType.objects.get_for_model(self.__class__)
        return urlresolvers.reverse("admin:%s_%s_change" % (content_type.app_label, content_type.model),
                                    args=(self.id,))

    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        return reverse('blogweb_blog:detail_entry', args=[str(self.slug)])

    def es_publicado(self):
        """
        Return True if the entry is publicly accessible.
        """
        return self.visible and self.fecha_publicacion <= datetime.datetime.now()

    es_publicado.boolean = True

    def publicado(self):
        return self.objects.activo().filter(fecha_publicacion__lte=datetime.datetime.now)

    @property
    def _resumen(self):
        return truncatechars(self.resumen, 150)

    def primera_imagen(self):
        return self.imagen_entrada.first()

    def __unicode__(self):
        return '%s, %s' % (self.titulo, self.autor)

    class Meta:
        ordering = ('-fecha_publicacion',)
        get_latest_by = 'fecha_publicacion'
        verbose_name = _('entrada')
        verbose_name_plural = _('entradas')


class Documento(models.Model):
    entrada = models.ForeignKey(Entrada, verbose_name=_('entrada'), related_name='documento_entrada')
    nombre = models.CharField(_('nombre'), max_length=100, blank=True, null=True)
    archivo = models.FileField(_('archivo'), upload_to='uploads/D/%Y/%m/%d/')

    def __unicode__(self):
        if self.nombre:
            return '%s' % self.nombre
        else:
            return basename(self.archivo.name)

    class Meta:
        verbose_name = _('documento')
        verbose_name_plural = _('documentos')


class Imagen(models.Model):
    entrada = models.ForeignKey(Entrada, verbose_name=_('entrada'), related_name='imagen_entrada')
    nombre = models.CharField(_('nombre'), max_length=100, blank=True, null=True,
                              help_text='ej: Horario, tickets, presentación, etc')
    archivo = models.FileField(_('archivo'), upload_to='uploads/I/%Y/%m/%d/')

    def __unicode__(self):
        if self.nombre:
            return '%s' % self.nombre
        else:
            return basename(self.archivo.name)

    class Meta:
        verbose_name = _('imagen')
        verbose_name_plural = _('imagenes')


class Video(models.Model):
    entrada = models.ForeignKey(Entrada, verbose_name=_('entrada'), related_name='video_entrada')
    nombre = models.CharField(_('nombre'), max_length=100, blank=True, null=True)
    archivo = models.FileField(_('archivo'), upload_to='uploads/V/%Y/%m/%d/')

    def __unicode__(self):
        if self.nombre:
            return '%s' % self.nombre
        else:
            return basename(self.archivo.name)

    class Meta:
        verbose_name = _('video')
        verbose_name_plural = _('videos')

blog/views.py
# coding=utf-8

import datetime
from django.shortcuts import render, get_object_or_404
from blog.models import Entrada, Etiqueta
from contact.views import form_contact
from django.utils.translation import ugettext as _


def home(request):
    ultimas_entradas = Entrada.objects.publicado()[:30]
    return render(request, 'blog/list.html', {
        'titulo': 'Todas las Entradas',
        'subtitulo': 'Noticias, proyectos, post y eventos',
        'descripcion': 'Descripción',
        'last_entries': ultimas_entradas,
        'all_tags': Etiqueta.objects.all(),
        'all_entries': Entrada.objects.publicado()[:30],
        'contact': form_contact(request=request),
    })


def list_author(request, username):
    last_entries = Entrada.objects.publicado().filter(
        autor__username=username)[:30]
    return render(request, 'blog/list.html', {
        'last_entries': last_entries,
        'Tag.objects.all()': Entrada.objects.all(),
        'all_entries': Entrada.objects.publicado()[:30],
        'contact': form_contact(request=request),
    })


def list_tag(request, slug):
    ultimas_entradas = Entrada.objects.publicado()[:30]
    return render(request, 'blog/list.html', {
        'last_entries': ultimas_entradas,
        'Tag.objects.all()': Entrada.objects.all(),
        'all_entries': Entrada.objects.publicado()[:30],
        'contact': form_contact(request=request),
    })


def detail_entry(request, slug):
    entrada = get_object_or_404(Entrada, slug=slug)
    last_entries = Entrada.objects.publicado()[:30]
    return render(request, 'blog/detail.html', {
        'entrada': entrada,
        'last_entries': last_entries,
        'all_tags': Etiqueta.objects.all(),
        'all_entries': Entrada.objects.publicado()[:30],
        'contact': form_contact(request=request),
    })

templates/blog/detail.html
{% extends 'web/base.html' %}
{% load staticfiles thumbnail cache i18n %}
{% block main %}
    <section class="blog-main section scrollspy">
        <div class="detail-cabecera parallax-container valign-wrapper">
            <div class="section no-pad-bot">
                <div class="container white-text padding-top-med">
                    <div class="header">{{ entrada.get_tipo_publicacion_display }}</div>
                    <div class="subheader">{{ entrada.autor.first_name }} {{ entrada.autor.last_name }}</div>
                    <div class="right"><a class="black-text" href="{% url 'blog-app:list_author' entrada.autor.username %}">Ver
                        más de este autor</a></div>
                </div>
            </div>
            <div class="parallax"><img src="{% static 'img/sea-2322517_1920.jpg' %}"></div>
        </div>
    </section>
    <div class="blog-main fondo-gris-1 padding-top-med padding-bot-min">
        <div class="container">
            <div class="row">
                <div class="col l4 m12 right aside">
                    <div class="container">
                        <div class="container">
                            <div class="title">{% trans 'Etiquetas' %}</div>
                            <div class="chip">
                                <a href="{% url 'blog-app:home' %}"
                                   class="black-text">Todas</a>
                            </div>
                            {% for etiqueta in all_tags %}
                                <div class="chip">
                                    <a href="{% url 'blog-app:list_tag' etiqueta.slug %}"
                                       class="black-text">{{ etiqueta.titulo|title }}</a>
                                </div>
                            {% endfor %}
                            <div class="title">{% trans 'Post recientes' %}</div>
                            <hr class="hr-1">
                            {% for entrada in all_entries %}
                                {% if entrada.url_externa %}
                                    <a href="{{ entrada.url_externa }}" class="black-text">
                                        <div class="entrada padding-top-min padding-bot-min">
                                            <div class="title">{{ entrada.headline }} <i
                                                    class="material-icons right">open_in_new</i>
                                            </div>
                                            <div class="date">{{ entrada.fecha_publicacion }}</div>
                                            <hr class="hr-2">
                                        </div>
                                    </a>
                                {% else %}
                                    <a href="{{ entrada.get_absolute_url }}" class="black-text">
                                        <div class="entrada padding-top-min padding-bot-min">
                                            <div class="title">{{ entrada.subtitulo }}</div>
                                            <div class="date">{{ entrada.fecha_publicacion }}</div>
                                            <hr class="hr-2">
                                        </div>
                                    </a>
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="col l8 m12 card-panel white">
                    <h3 class="headline">{{ entrada.subtitulo }}
                        {% if request.user.is_superuser %}
                            <a class="right btn-floating waves-effect btn-flat color-1 pulse"
                               href="{{ entrada.get_admin_url }}">
                                <i class="material-icons">mode_edit</i></a>
                        {% endif %}
                    </h3>
                    <h4 class="subheadline">{{ entrada.subtitulo }}</h4>
                    <div class="row">
                        <h5 class="right-align pub-date">
                            {% if entrada.autor.first_name and entrada.autor.last_name %}
                                <i class="material-icons tiny">people</i> {{ entrada.autor.first_name }}
                                {{ entrada.autor.last_name }}
                            {% endif %}
                            {% if entrada.ubicacion %}
                                <i class="material-icons tiny">location_on</i> {{ entrada.ubicacion }}
                            {% endif %}
                            <i class="material-icons tiny">date_range</i> {{ entrada.fecha_publicacion }}
                        </h5>
                    </div>
                    <div class="tags">
                        Etiquetas:
                        {% for tag in entrada.etiqueta.select_related %}
                            <div class="chip">{{ tag.titulo|title }}</div>
                        {% endfor %}
                    </div>
                    <div class="right-align">
                        <h5 class="right-align pub-date location"></h5>
                    </div>
                    {% if entrada.resumen %}
                        <hr>
                        <div class="summary">{{ entrada.resumen }}</div>
                    {% endif %}
                    {% if entrada.imagen_entrada.select_related %}
                        <hr>
                        <div class="subheadline">Galería:</div>
                        <div class="detail-slider slider">
                            <ul class="slides">
                                {% for image in entrada.imagen_entrada.select_related %}
                                    <li>
                                        <img src="{% thumbnail image.archivo 'detalle-miniatura' %}">
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    {% endif %}
                    <hr>
                    <div class="content padding-bot-med">
                        {{ entrada.contenido|safe }}
                    </div>
                    {% if entrada.archivo_entrada.select_related %}
                        <div class="galery-files padding-top-med">
                            <div class="subheadline">{% trans 'Archivos' %}:</div>
                            {% for foo in entrada.archivo_entrada.select_related %}
                                <a download="" href="{{ MEDIA_URL }}{{ foo.archivo }}"
                                   class="chip">{{ foo }}</a>
                            {% endfor %}
                        </div>
                    {% endif %}
                    {% if entrada.video_entrada.select_related %}
                        <div class="gallery-videos padding-bot-min padding-top-med">
                            <div class="subheadline">{% trans 'Videos' %}:</div>
                            <ul id="tabs-swipe-demo" class="tabs">
                                {% for video in entrada.video_entrada.select_related %}
                                    <li class="tab col s3"><a
                                            href="#test-swipe-video-{{ video.id }}"> {{ video }}</a>
                                    </li>
                                {% endfor %}
                            </ul>
                            {% for video in entrada.video_entrada.select_related %}
                                <div id="test-swipe-video-{{ video.id }}" class="col s12 height-video">
                                    <video preload=auto controls class="responsive-video">
                                        <source src="{{ MEDIA_URL }}{{ video.archivo }}" type="video/mp4">
                                    </video>
                                </div>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
                {% if entrada.comentarios_facebook %}
                    <div id="fb-root"></div>
                    <script>(function (d, s, id) {
                        var js, fjs = d.getElementsByTagName(s)[0];
                        if (d.getElementById(id)) return;
                        js = d.createElement(s);
                        js.id = id;
                        js.src = "//connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v2.10&appId=222427671463375";
                        fjs.parentNode.insertBefore(js, fjs);
                    }(document, 'script', 'facebook-jssdk'));</script>
                    <div class="col l8 m12 s12 card-panel white">
                        <h3 class="headline">{% trans 'Comentarios' %}:</h3>
                        <div class="fb-comments"
                             data-href="http://www.okeanos.cl/comentario/{{ entrada.slug }}"
                             data-width="100%" data-numposts="5"></div>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}
{% block extra-js %}
{% endblock %}

templates/blog/list.html
{% extends 'web/base.html' %}
{% load staticfiles thumbnail i18n %}

{% block main %}
    <section class="blog-main section scrollspy" id="blog">
        <div class="parallax-container valign-wrapper">
            <div class="section no-pad-bot">
                <div class="container white-text">
                    <div class="header">{{ last_entries.last.autor.first_name }} {{ last_entries.last.autor.last_name }}</div>
                    <div class="subheader">{% trans 'Ultima publicación:' %} {{ last_entries.last.fecha_publicacion }}</div>
                    <div class="right">{% trans 'Usuario:' %} {{ last_entries.last.autor }}</div>
                </div>
            </div>
            <div class="parallax"><img src="{% static 'img/sunrise-1756274_1920.jpg' %}"></div>
        </div>
    </section>
    <div class="blog-main white padding-top-med padding-bot-med">
        <div class="container">
            <div class="row">
                <div class="col l4 m12 right aside">
                    <div class="container">
                        <div class="container">
                            <div class="title">{% trans 'Etiquetas' %}</div>
                            <div class="chip">
                                <a href="{% url 'blog-app:home' %}"
                                   class="black-text">{% trans 'Todas' %}</a>
                            </div>
                            {% for tag in all_tags %}
                                <div class="chip">
                                    <a href="{% url 'blog-app:list_tag' tag.slug %}"
                                       class="black-text">{{ tag.titulo|title }}</a>
                                </div>
                            {% endfor %}
                            <div class="title padding-top-min">{% trans 'Post Recientes' %}</div>
                            <hr class="hr-1">
                            {% for entrada in all_entries %}
                                {% if entrada.external_url %}
                                    <a href="{{ entrada.external_url }}" class="black-text">
                                        <div class="entrada padding-top-min padding-bot-min">
                                            <div class="title">{{ entrada.titulo }} <i class="material-icons right">open_in_new</i>
                                            </div>
                                            <div class="date">{{ entrada.pub_date }}</div>
                                            <hr class="hr-2">
                                        </div>
                                    </a>
                                {% else %}
                                    <a href="{{ entrada.get_absolute_url }}" class="black-text">
                                        <div class="entrada padding-top-min padding-bot-min">
                                            <div class="title">{{ entrada.titulo }}</div>
                                            <div class="date">{{ entrada.fecha_publicacion }}</div>
                                            <hr class="hr-2">
                                        </div>
                                    </a>
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="col l8 m12">
                    <div class="row container-masonry">
                        {% for entrada in last_entries %}
                            <div class="col s12 m6 item">
                                <div class="card">
                                    <div class="card-image">
                                        {% if entrada.primera_imagen %}
                                            <img src="{% thumbnail entrada.primera_imagen.archivo 'card-img' %}">
                                        {% else %}
                                            <img src="{% static 'img/sunrise-1756274_1920.jpg' %}">
                                        {% endif %}
                                        {% if entrada.external_url %}
                                            <a class="btn-floating btn-large halfway-fab waves-effect waves-light color-1 pulse"
                                               href="{{ entrada.url_externa }}" target="_blank">
                                                <i class="material-icons">link</i>
                                            </a>
                                        {% else %}
                                            <a class="btn-floating btn-large halfway-fab waves-effect waves-light color-1 pulse"
                                               href="{{ entrada.get_absolute_url }}">
                                                <i class="material-icons">add</i>
                                            </a>
                                        {% endif %}
                                    </div>
                                    <div class="card-content">
                                        <span class="card-title">{{ entrada.titulo }}</span>
                                        <p>{{ entrada.subtitulo }}</p>
                                    </div>
                                </div>
                            </div>
                        {% empty %}
                            <div class="title">{% trans 'No existen post relacionados' %}</div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}